### ISSUE TITLE
[US-01] List of products

### ISSUE THREAD

**Issue by lukemt** [lukemt/capstone-project#1]
## Value Statement
As a User I want see a list of products 

## Mockup:
![image](https://user-images.githubusercontent.com/3893274/136210662-c93d0f36-f392-4c0e-a6f2-5f12678070ce.png)

## Acceptance Criteria
- App shows a list of Products
- Correct styling
- Show Fotos of Products

## Subtasks
- [ ] Get the assets of the products with photos
- [ ] Create React App
- [ ] Create Component
- [ ] Use Data from Array
- [ ] Write Component Tests
- [ ] Add Component to App
- [ ] Add Styling

## Complexity
- medium
